param(
    [string]$SourceSingle = "C:\Users\oofer\Downloads\Universal-GLM-5.2-V9.lua",
    [string]$ProjectRoot = "C:\Users\oofer\Downloads\Potatools-dev",
    [int]$MaxLocalTokens = 180,
    [int]$MaxChars = 450000
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path -LiteralPath $SourceSingle)) {
    throw "Missing source hub: $SourceSingle"
}

$partsDir = Join-Path $ProjectRoot "modules\original_parts"
$manifestPath = Join-Path $ProjectRoot "modules\original_manifest.lua"

if (-not (Test-Path -LiteralPath $partsDir)) {
    New-Item -ItemType Directory -Path $partsDir | Out-Null
}

Get-ChildItem -LiteralPath $partsDir -File -Filter "part_*.lua" | Remove-Item -Force

$source = [System.IO.File]::ReadAllText($SourceSingle)
$hash = (Get-FileHash -Algorithm SHA256 -LiteralPath $SourceSingle).Hash

$parts = New-Object System.Collections.Generic.List[object]
$start = 0
$partIndex = 1
$length = $source.Length

while ($start -lt $length) {
    $take = [Math]::Min($MaxChars, $length - $start)
    $candidate = $source.Substring($start, $take)
    $localCount = ([regex]::Matches($candidate, '\blocal\b')).Count

    while ($localCount -gt $MaxLocalTokens -and $take -gt 2048) {
        $take = [Math]::Floor($take * 0.85)
        $candidate = $source.Substring($start, $take)
        $localCount = ([regex]::Matches($candidate, '\blocal\b')).Count
    }

    if ($localCount -gt $MaxLocalTokens) {
        throw "Cannot split below $MaxLocalTokens local tokens near offset $start"
    }

    $name = "part_{0:D4}.lua" -f $partIndex
    $path = Join-Path $partsDir $name
    [System.IO.File]::WriteAllText($path, $candidate, [System.Text.UTF8Encoding]::new($false))

    $relative = "modules/original_parts/$name"
    $parts.Add([pscustomobject]@{
        path = $relative
        length = $candidate.Length
        locals = $localCount
    })

    $start += $take
    $partIndex += 1
}

$manifest = New-Object System.Collections.Generic.List[string]
$manifest.Add("-- Generated by scripts/split_exact_original.ps1")
$manifest.Add("return {")
$manifest.Add("    source = `"Universal-GLM-5.2-V9.lua`",")
$manifest.Add("    length = $($source.Length),")
$manifest.Add("    sha256 = `"$hash`",")
$manifest.Add("    parts = {")
foreach ($part in $parts) {
    $manifest.Add("        { path = `"$($part.path)`", length = $($part.length), locals = $($part.locals) },")
}
$manifest.Add("    },")
$manifest.Add("}")
[System.IO.File]::WriteAllText($manifestPath, ($manifest -join "`r`n") + "`r`n", [System.Text.UTF8Encoding]::new($false))

$rebuilt = New-Object System.Text.StringBuilder
foreach ($part in $parts) {
    $fullPath = Join-Path $ProjectRoot ($part.path -replace '/', '\')
    [void]$rebuilt.Append([System.IO.File]::ReadAllText($fullPath))
}

if ($rebuilt.ToString() -ne $source) {
    throw "Exact split verification failed: rebuilt source differs from original"
}

Write-Host "Exact split complete."
Write-Host "Parts: $($parts.Count)"
Write-Host "Source length: $($source.Length)"
Write-Host "SHA256: $hash"
Write-Host "Manifest: $manifestPath"
